# Site settings
title: Wagner Lopes
twitter_username: wagnerl0pes
name: Wagner L. B. A. Lopes

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: DZone
   url: https://dzone.com/users/977271/wagnerluislopes.html
 - title: GitHub
   url: https://github.com/wagnerlopes
 - title: LinkedIn
   url: https://www.linkedin.com/in/wagnerluislopes
 - title: StackOverflow
   url: http://stackoverflow.com/users/7103811/wagner-lopes

#Any buzzword skills you want to include
skills:
 - Java
 - JavaScript
 - JPA
 - Oracle
 - Maven
 - Rest API
 - Spring Boot
 - Spring MVC
 - SQL
 
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: http://wagnerlopes.blogspot.com/feeds/posts/default

#Work experience is required
roles:
 - title: Senior Arch and Programmer
   start: 2026
   end: Ongoing
   employer: self-employed
   description: Owner Consultant.
 - title: Senior Arch and Programmer
   start: 2001
   end: 2025
   employer: Brazilian Army
   description: Java Programmer.
 - title: Oracle Programmer
   start: 1995
   end: 2001
   employer: Brazilian Army
   description: Oracle PL/SQL Programmer.
 - title: Artillery Officer
   start: 1991
   end: 1995
   employer: Brazilian Army
   description: A range of functional and technical militaries roles.

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Education is required
education:
 - level: System Analysis and Development
   date: 1994
   school: Faculdades Associadas de São Paulo

 - level: Java Programmer by Sun Microsystems
   date: 1999
   school: SESC (Sun Microsystems)

#This section is optional (as is the image link below)
#coursera:
#   profileurl:
#   courses:
#    - title: ?
#      link: ?
#      optionalimage: ?
#      date: ?

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018

#List of interesting Github repo/projects to include - optional
github:
 - wagnerlopes/babilonia

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/7103811/wagner-lopes
   flairimageurl: http://stackoverflow.com/users/flair/7103811.png

#Mobile apps section is optional
#apps:
# - name: 
#   platform:
#   url: 
#   description: 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring Framework, Spring-security, JPA (EclipseLink and HIbernate) in addition to others. <br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on Spring MVC framework. I have also worked with some client side technology, having used JavaScript, Bootstrap and Font Awesome.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with Git, Maven and CI. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge in last twenty years working in enterprise projects. <br/><br/>

#intro: |
#  I am an engineer with 15 years experience working in technology. I have primarily worked on the JVM, but have worked across a broad range of technologies thereon: Java, Groovy, Android, Coldfusion and most recently Scala. As well as spending a reasonable amount of time building applications for the web, which has given me an exposure to a range of javascript technologies over the years, through jQuery, extjs, knockout, backbone and most recently to React. <br/><br/>
#  I enjoy building interesting products, with a good Product Management focus and a good emphasis on good engineering principles and clean code (having worked across differing languages on the JVM, I recognise that good code is contextual).<br/><br/>
#  I have worked in large scale consultancy roles across Europe as well as a mix of startup experience (including one that was acquired) and I am currently the Chief Technology Officer at a legal-tech startup called <a href="https://www.basementcrowd.com" target="_blank">Basement Crowd</a> where we are building innovative products to serve the legal industry.
